### ISSUE TITLE
LoadedEncodeMotifs error in python3

### ISSUE THREAD

**Issue by krrome** [kundajelab/simdna#3]
Loading of encode motifs with LoadedEncodeMotifs(ENCODE_MOTIFS_PATH, pseudocountProb=0.001) does not work in python3. Conversion of read lines to unicode solves the problem, but will break functionality in python2.7. As a quick fix for me I just added "line = line.decode("utf-8")" here: https://github.com/kundajelab/simdna/blob/fb9d150294fec4a6977f3f91987ac80f4612152b/simdna/util.py#L101

**Comment by rbharath** [comment]
Just ran into this in https://github.com/deepchem/deepchem/pull/1008. Would you folks be amenable to a PR adding this fix in?

**Comment by AvantiShri** [comment]
Yes, sorry for not getting to it earlier. Are you guys planning to add the PR or should I? Also, you're using version 0.3 right?

**Comment by lilleswing** [comment]
Fix is included in this PR
https://github.com/kundajelab/simdna/pull/5

**Comment by AvantiShri** [comment]
Cool, just merged.
