### ISSUE TITLE
simulations.py gone in head?

### ISSUE THREAD

**Issue by rbharath** [kundajelab/simdna#4]
I'm working through the DRAGONN tutorial and noticed the following line:

```
from simdna import simulations
```

This file looks to be gone in HEAD. Is there another file I should use with the same functionality?

**Comment by AvantiShri** [comment]
It was removed after version 0.3 because it was highly DRAGONN specific, but you can get it from the version 0.3 tag here: https://github.com/kundajelab/simdna/tree/0.3/simdna

**Comment by rbharath** [comment]
@AvantiShri Thanks for the quick response!
